### ISSUE TITLE
Ошибка выполнения Clio push-pkg

### ISSUE THREAD

**Issue by HillReywer** [Advance-Technologies-Foundation/clio#170]
Добрый день, 

при выполнении команды clio push-pkg мы получаем ошибку – The remote server returned an error: (404) Not Found, так же ошибка воспроизводиться при выполнении Clio ping. Утилита Clio и приложение Studio развернуто на базе платформы OpenShift, данные продукты находятся в разных подах. При этом регистрация приложения через команду  reg-web-app с использованием DNS имени и связки логин / пароль происходит корректно. Ниже пример сообщения об ошибке. 

```
sh-4.4$ clio ping dev
Ping http://****/O/ping ...
System.Wet.WebException: The remote server returned an error: (404) Wot Found.
at System.Wet.HttpWebRequest.GetResponse() in /_/src/System.Wet.Requests/src/System/Wet/HttpWebRequest.cs:line 1004 at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request) at Creatio.Client.CreatioClient.PingApp()
at Creatio.Client.CreatioClient.CreateCreatioRequest(String url, String requestData, Int32 requestTimeout) at Creatio.Client.CreatioClient.ExecutePostRequest(String url, String requestData, Int32 requestTimeout) at Clio.Common.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout) at Clio.Command.RemoteCommand'1.ExecuteRemoteCommand(TEnvironmentOptions options) at Clio.Command.RemoteCommand'1.Execute(TEnvironmentOptions options)
```

**Comment by iwebcas** [comment]
Добрый день.
Если вы подключаетесь к приложению под .NetCore, то убедитесь пожалуйста, что в вашем "appsettings.json" есть параметр "IsNetCore" и он установлен в "true".
Чтобы посмотреть где находится этот конфиг и увидеть его содержимое, достаточно написать следующее:
clio show-web-app-list
Так же убедитесь пожалуйста, что ваш сайт пингуется любыми другими средствами, кроме Clio.

**Comment by HillReywer** [comment]
@iwebcas Спасибо, push починили, но теперь вылезла другая ошибка. Сам сайт доступен, и работает. Ping до него тоже есть из pods с Clio. 
```
sh-4.4$ clio push-pkg Equip Uploading...
Uploaded
Install Equip.gz ...
Installation log:
2020-10-15 12:39:21,086 Загрузка файла: Equip.gz 100%
2020-10-15 12:39:22,128 Подготовка пакетов к инсталляции
2020-10-15 12:39:22,132 Начало установки пакетов
2020-10-15 12:39:22,161 System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at Systern.Uri.CreateThis(String uri, Boolean doncEscape, UriKind uriKind) in /_/src/System.Private.Uri/src/System/UriExt.cs:line 37
at System.Uri..ctor(String uriString) in /_/src/System.Private.Uri/src/System/Uri.cs:line 339
at Terrasoft.Core.Packages.PackageStorageFactory.Create(String storageDirectory, String sourceRepositoryUri) in /opt/buildagent/work/Applica
tionCoreLinux/TSBpm/Src/Lib/Terrasoft.Core/Packages/PackageStorageFactory.cs:line 29
at Terrasoft.Core.Applnstallation.Packages.Operations.PackageZipOperations.Load() in /opt/buildagent/work/ApplicationCoreLinux/TSBpm/Src/Lib
/Terrasoft.Core.AppInstallation/Packages/0perations/Package2ip0perations.cs:line 65
at Terrasoft.Core.Applnstallation.Packages.PackageZipInstaller.Install(String sourcePath, String destinationPath, PackageInstallOptions inst
allOptions) in /opt/buildagent/vork/ApplicationCoreLinux/TSBpm/Src/Lib/Terrasoft.Core.AppInstallation/Packages/PackageZipInstaller.cs:line 55 at Terrasoft.Core.ServiceHodelContract.Packagelnstaller.PackagelnstallerServicelnternal.InstallFromUnzippedFiles(String sourcePath, String t empFilesPath, PackageInstallOptions packagelnstallOptions) in /opt/buildagent/vork/ApplicationCoreLinux/TSBpm/Src/Lib/Terrasoft.Core.ServiceHod
elContract/Packagelnstaller/PackagelnstallerServicelnternal.cs:line 101
at Terrasoft.Core.ServiceHodelContract.Packagelnstaller.PackagelnstallerServicelnternal.InstallFromArchive(String uploadingFilePath) in /opt
/buildagent/work/ApplicationCoreLinux/TSBpm/Src/Lib/Terrasoft.Core.ServiceHodelContract/PackageInstaller/PackageInstallerServiceInternal^^|^^ W i n d o w s
at Terrasoft.Core.ServiceHodelContract.Packagelnstaller.PackagelnstallerServicelnternal.Oc__DisplayClass23_0.<InstallPackage>b__0() £iC>>f6|>fcystem in Control Panel to activate /buildagent/uork/ApplicationCoreLinux/TSBpm/Src/Lib/Terrasoft.Core.ServiceHodelContract/PackageInstaller/PackageInstallerServiceInternalvV*Mii£»\$
e 155
at Terrasoft.Core.ServiceHodelContract.Packagelnstaller.BaselnstallerServicelnternal.InvokeUithLogging[TResult](Func'l action) in /opt/build agent/work/ApplicationCoreLinux/TSBpm/Src/Lib/Terrasoft.Core.ServiceHodelContract/Packagelnstaller/BaselnstallerServicelnternal.cs:line 135
The remote server returned an error: (500) Internal Server Error.
```

Заливка пакета происходит по http или по https?

**Comment by iwebcas** [comment]
@HillReywer 
Тут может быть несколько вариантов.
1. Некорректный путь к временой папке.
2. У приложения нет прав на изменение указанной папки.
3. (маловероятный) Было изменено имя gz файла (имя файла должно соответствовать имени, указанному в дескрипторе + .gz)
Чтобы подтвердить или исключить первые два пункта, попробуй установить ваш пакет из страницы установки приложений.
p.s. Путь к временной папке можно посмотреть/изменить в конфиге ("ConnectionStrings.config", параметр называется "tempDirectoryPath").

**Comment by HillReywer** [comment]
@iwebcas Да, спасибо, оказалось первый вариант, пути указаны были под Windows, а нужны под Linux
