### ISSUE TITLE
UploadFile. Падает при большом архиве

### ISSUE THREAD

**Issue by Kleva** [Advance-Technologies-Foundation/clio#195]
Ребятки, привет!

Падает UploadFile при попытке загрузить архив (у меня 40 Мбайт) на linux-сборку 7.18.4.1534_SalesTeam_Marketing_CustomerCenter_Linux_Softkey_PostgreSQL_ENU_NetCore.zip

При этом мелкие архивы загружаются корректно
Установка этого же пакета на Windows-сборку проходит корректно. 

На Linux-сборку этот же большой архив также корректно устанавливается через UI

Стек ошибки 
 at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request) in /Users/ivankleva/Downloads/clio-master/clio/creatioclient/ATFWebRequestExtensions.cs:line 14
   at Creatio.Client.CreatioClient.UploadFile(String url, String filePath) in /Users/ivankleva/Downloads/clio-master/clio/creatioclient/CreatioClient.cs:line 247
   at Clio.Common.CreatioClientAdapter.UploadFile(String url, String filePath) in /Users/ivankleva/Downloads/clio-master/clio/Common/IApplicationClient.cs:line 53
   at Clio.Package.PackageInstaller.UploadPackage(String filePath) in /Users/ivankleva/Downloads/clio-master/clio/Package/PackageInstaller.cs:line 107
   at Clio.Package.PackageInstaller.InstallPackedPackage(String filePath) in /Users/ivankleva/Downloads/clio-master/clio/Package/PackageInstaller.cs:line 181
   at Clio.Package.PackageInstaller.InstallPackage(String packagePackedFileOrFolderPath) in /Users/ivankleva/Downloads/clio-master/clio/Package/PackageInstaller.cs:line 210
   at Clio.Package.PackageInstaller.Install(String packagePath, String reportPath) in /Users/ivankleva/Downloads/clio-master/clio/Package/PackageInstaller.cs:line 229
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options) in /Users/ivankleva/Downloads/clio-master/clio/Command/PushPackageCommand.cs:line 33

**Comment by TheEmperor80** [comment]
@Kleva Did you manage to get around this? We have the very same problem! Thanks,
