### ISSUE TITLE
Upload failing in Azure Devops

### ISSUE THREAD

**Issue by qualysoft-nikcevic** [Advance-Technologies-Foundation/clio#196]
Hi,

I am trying to setup CI/CD pipeline in AzureDevOps. Currently I am testing with Creatio free online demo 7.18.5, and with Clio 2.0.0.15. 

Commands clio push and clio restart-web-app are failing when they are run through Azure pipeline. Default windows Azure agent is used for the pipeline.

Errors are:
clio push-pkg -e DEV-ENV packageName.gz
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\018a26f6-a6e5-4a91-b86b-8b9391639085.cmd""
Uploading...
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.CreatioClient.Login()
   at Creatio.Client.CreatioClient.CreateCreatioRequest(String url, String requestData, Int32 requestTimeout)
   at Creatio.Client.CreatioClient.UploadFile(String url, String filePath)
   at Clio.Common.CreatioClientAdapter.UploadFile(String url, String filePath)
   at Clio.Package.PackageInstaller.UploadPackage(String filePath)
   at Clio.Package.PackageInstaller.InstallPackedPackage(String filePath)
   at Clio.Package.PackageInstaller.InstallPackage(String packagePackedFileOrFolderPath)
   at Clio.Package.PackageInstaller.Install(String packagePath, String reportPath)
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)
##[error]Cmd.exe exited with code '1'.

clio restart-web-app -e DEV-ENV
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\85680522-8bec-44da-a84d-16a2cb0214db.cmd""
System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.CreatioClient.Login()
   at Creatio.Client.CreatioClient.CreateCreatioRequest(String url, String requestData, Int32 requestTimeout)
   at Creatio.Client.CreatioClient.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Common.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Command.RemoteCommand`1.ExecuteRemoteCommand(TEnvironmentOptions options)
   at Clio.Command.RemoteCommand`1.Execute(TEnvironmentOptions options)

Before these steps,  clio register and clio ping command are completed ok. What could be the problem here?

Thank you.

**Comment by IlyaChubko** [comment]
Hello. I think not exist DEV-ENV environment in scope. Can you try full command?
clio push-pkg -u <url> -l <user> -p <password> packageName.gz

**Comment by qualysoft-nikcevic** [comment]
Hello Ilya,

Thank you for comment. I've tried full command for push pkg, but I still get error:

clio push-pkg packageName.gz -u "https://111390-crm-bundle.creatio.com" -l "Supervisor" -p "jelena"
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\68460ad6-a4da-432a-a4a1-67e60e40b316.cmd""
Uploading...
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.CreatioClient.Login()
   at Creatio.Client.CreatioClient.CreateCreatioRequest(String url, String requestData, Int32 requestTimeout)
   at Creatio.Client.CreatioClient.UploadFile(String url, String filePath)
   at Clio.Common.CreatioClientAdapter.UploadFile(String url, String filePath)
   at Clio.Package.PackageInstaller.UploadPackage(String filePath)
   at Clio.Package.PackageInstaller.InstallPackedPackage(String filePath)
   at Clio.Package.PackageInstaller.InstallPackage(String packagePackedFileOrFolderPath)
   at Clio.Package.PackageInstaller.Install(String packagePath, String reportPath)
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)

**Comment by IlyaChubko** [comment]
Can you check login/password?

**Comment by qualysoft-nikcevic** [comment]
Login is ok. The commands are only failing when they are run in Azure pipeline with microsoft-hosted agent. When I run the same clio commands from my Notebook, then they work. Are you aware of anything specific that we should setup for windows microsoft-hosted agent?
Thank you.

**Comment by IlyaChubko** [comment]
1) Try execute command without double quotas:
clio push-pkg packageName.gz -u our_url -l our_user -p our_password
2) Try add -i parameter
linux - true
win - false
clio push-pkg packageName.gz -u our_url -l our_user -p our_password -i false

**Comment by qualysoft-nikcevic** [comment]
Hi Ilya,
 clio push-pkg packageName.gz -u our_url -l our_user -p our_password -i false work better, with windows azure agent. I'll continue some further tests. Thank you for support.
