### ISSUE TITLE
Error trying to install package using clio

### ISSUE THREAD

**Issue by unusen** [Advance-Technologies-Foundation/clio#231]
I folks! I'm getting an error trying to install clio when I have at least one schema; this error happens only if I create the GZ using clio ( generate-pkg-zip). If I tried to install a zip file generated by export package it working as expected.
Below the error:

2023-06-02 02:45:11,752 Error occured while performing operation on "BGEntity_fd6a5b7" item, UId = 41292853-5c85-46ee-b56e-96b7b73083d6.
2023-06-02 02:45:11,752 System.IO.DirectoryNotFoundException: Could not find a part of the path 'metadata.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Terrasoft.Common.IO.FileStreamWrapper.Create(String path, FileMode mode, FileAccess access, FileShare share)
   at Terrasoft.Core.Packages.PackageContentFileProvider.ReadTextFile(String filePath)
   at Terrasoft.Core.Packages.PackageContentFileProvider.GetSchemaStreamValues(Package package, SchemaDescriptor schema)
   at Terrasoft.Core.Packages.PackageDBStorage.InitializeSysSchema(Guid sysPackageId, Package package, SchemaDescriptor schema, IPackageContentProvider contentProvider) 
   at Terrasoft.Core.Packages.PackageDBStorage.SaveSchema(Guid sysPackageId, Package package, SchemaDescriptor schema, IPackageContentProvider contentProvider)
   at Terrasoft.Core.Packages.PackageDBStorage.<>c__DisplayClass482_1.<SavePackageSchemas>b__0()
   at Terrasoft.Core.Packages.PackageStorage.SafeItemOperation(Descriptor descriptor, Action action)
2023-06-02 02:45:11,752 Files saved in package "Test"

Appreciate your help in advance.
Regards

**Comment by kirillkrylov** [comment]
@unusen 
generate-pkg-zip expects a gz file output when working with **one** package. 
For example when you do the following 
`clio generate-pkg-zip PKG_Name -d PKG_Name.zip ` it will fail, however 
`clio generate-pkg-zip PKG_Name -d PKG_Name.gz` will succeed.

We recommend to use alias compress for generate-pkg-zip command, for example, use the following
`clio compress PKG_Name -d PKG_Name.gz`

When working with multiple packages, and wish to create a bundle you can use compress command to generate zip file. 
`clio compress -p PKG_Name_One,PKG_Name_Two,PKG_Name_etc -d bundle.zip`
> Make sure to not have any whitespaces between package names
