### ISSUE TITLE
Ошибки при утановке пакетов что имеют продолжительное время установки

### ISSUE THREAD

**Issue by fejdraus** [Advance-Technologies-Foundation/clio#232]
При установке или выполнению задач что требуют продолжительного ожидания выдает ошибку ожидания. Это происходит из-за использования библиотеки RestSharp в которой уже довольно продолжительное время сломана настройка ожидания ответа, и при достижении 100 секунд получаем разрыв. В своем проекте для Creatio удалось решить проблему использованием HttpClient в котором можно выставить вечное ожидание ответа, и ожидания в 15 минут проходят без проблем.

`Install TsiNotificationMaster.gz ...
Installation log:
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request)
   at Creatio.Client.CreatioClient.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Common.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Package.PackageInstaller.InstallPackageOnServer(String fileName, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.PackageInstaller.InstallPackageOnServerWithLogListener(String fileName, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.PackageInstaller.InstallPackedPackage(String filePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.PackageInstaller.InstallPackage(String packagePackedFileOrFolderPath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.PackageInstaller.Install(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)`

**Comment by vladimir-nikonov** [comment]
fixed in clio 6.0.1.30 and creatio.clent 1.0.15
