### ISSUE TITLE
During the installation of the package archive, an error occurs on version 6.0.1.30, but everything is okay on version 6.0.1.29.

### ISSUE THREAD

**Issue by grechushkinnn** [Advance-Technologies-Foundation/clio#233]
2023-06-23T14:51:37.1703491Z 2023-06-23 17:51:36,853 Загрузка файла: Pkg.zip 100%
2023-06-23T14:51:37.1768010Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
2023-06-23T14:51:37.1768444Z    at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
2023-06-23T14:51:37.1768967Z    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
2023-06-23T14:51:37.1770526Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2023-06-23T14:51:37.1771408Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2023-06-23T14:51:37.1772023Z    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
2023-06-23T14:51:37.1772531Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2023-06-23T14:51:37.1773059Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2023-06-23T14:51:37.1773494Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
2023-06-23T14:51:37.1774086Z    at Clio.Package.BasePackageInstaller.InstallPackageOnServerWithLogListener(String fileName, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
2023-06-23T14:51:37.1774833Z    at Clio.Package.BasePackageInstaller.InstallPackedPackage(String filePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
2023-06-23T14:51:37.1775706Z    at Clio.Package.BasePackageInstaller.InstallPackage(String packagePackedFileOrFolderPath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
2023-06-23T14:51:37.1776500Z    at Clio.Package.BasePackageInstaller.InternalInstall(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
2023-06-23T14:51:37.1777264Z    at Clio.Package.PackageInstaller.Install(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
2023-06-23T14:51:37.1777819Z    at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)

**Comment by vladimir-nikonov** [comment]
fixed in 6.0.31
