### ISSUE TITLE
clio.exe install .\BiogenesisBago -u *** -l *** -p ***

### ISSUE THREAD

**Issue by unusen** [Advance-Technologies-Foundation/clio#234]
Hi Team! how are you?
I'm experiecing an issue using Github actions trying to deploy my package with clio. The process raise an error but seems that the deploy finished as expected

_Prepare all required actions
Run ./.github/actions/clio-install
Run dotnet tool install clio --tool-path .\ClioTool;
You can invoke the tool using the following command: clio
Tool 'clio' (version '6.0.1.30') was successfully installed.
Run .\ClioTool\clio.exe install .\BiogenesisBago -u *** -l *** -p ***;
  .\ClioTool\clio.exe install .\BiogenesisBago -u *** -l *** -p ***;
  shell: C:\Windows\System3[2](https://github.com/unusen/BiogenesisBagoCreatio/actions/runs/5359270854/jobs/9722660581#step:4:2)\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
Uploading...
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request)
   at Creatio.Client.CreatioClient.PingApp(Int[32](https://github.com/unusen/BiogenesisBagoCreatio/actions/runs/5359270854/jobs/9722660581#step:4:35) pingTimeout)
   at Creatio.Client.CreatioClient.InitAuthCookie(Int32 requestTimeout)
   at Creatio.Client.CreatioClient.get_AuthCookie()
   at Creatio.Client.CreatioClient.CreateCreatioRequest(String url, String requestData, Int32 requestTimeout)
   at Creatio.Client.CreatioClient.UploadFile(String url, String filePath, Int32 defaultTimeout)
   at Clio.Common.CreatioClientAdapter.UploadFile(String url, String filePath)
   at Clio.Package.BasePackageInstaller.UploadPackage(String filePath, EnvironmentSettings environmentSettings)
   at Clio.Package.BasePackageInstaller.InstallPackedPackage(String filePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackageFromFolder(String packageFolderPath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackage(String packagePackedFileOrFolderPath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InternalInstall(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
   at Clio.Package.PackageInstaller.Install(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)
Error: Process completed with exit code 1._

Regards.

**Comment by vladimir-nikonov** [comment]
fixed in 6.0.31
