### ISSUE TITLE
После обновления до версии "6.0.1.30", пакеты перестали устанавливаться

### ISSUE THREAD

**Issue by fejdraus** [Advance-Technologies-Foundation/clio#235]
После обновления до версии "6.0.1.30", пакеты перестали устанавливаться

 clio push-pkg "Banza.AM.Model.gz" -u "http://localhost:8094/" -l "Supervisor" -p "Supervisor"

Uploading...
Uploaded
Backup process...
Backup completed
Install Banza.AM.Model.gz ...
Installation log:
2023-06-28 15:04:09,483 Загрузка файла: Banza.AM.Model.gz 100%
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Clio.Package.BasePackageInstaller.InstallPackageOnServerWithLogListener(String fileName, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackedPackage(String filePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackage(String packagePackedFileOrFolderPath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InternalInstall(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
   at Clio.Package.PackageInstaller.Install(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)

**Comment by vladimir-nikonov** [comment]
fixed in 6.0.31
