### ISSUE TITLE
clio pkg-to-db returns error on 6.0.1.31

### ISSUE THREAD

**Issue by AloneInChains** [Advance-Technologies-Foundation/clio#237]
Default environment is configured with file system development.
Calling command **clio pkg-to-db** raises error:

clio pkg-to-db
System.ArgumentNullException: Value cannot be null. (Parameter 'content')
   at System.Net.Http.StringContent.GetContentByteArray(String content, Encoding encoding)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at Creatio.Client.CreatioClient.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Common.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Package.FileDesignModeFileDesignModePackages.get_IsFileDesignModeUrl()
   at Clio.Package.FileDesignModeFileDesignModePackages.LoadPackagesToStorage(String endpoint, String storageName)
   at Clio.Package.FileDesignModeFileDesignModePackages.LoadPackagesToDb()
   at Clio.Command.LoadPackagesToDbCommand.Execute(EnvironmentOptions options)

**Comment by kirillkrylov** [comment]
@AloneInChains 
Please try the latest version (6.0.1.34)

**Comment by AloneInChains** [comment]
Seems to be fixed. Thanks!
