### ISSUE TITLE
Error using Clio and Git Actions - v 6.0.1.32

### ISSUE THREAD

**Issue by unusen** [Advance-Technologies-Foundation/clio#240]
Hi Team! How are you? We are still experiencing issues using clio on Git Actions. Below the issue:

Prepare all required actions
Run ./.github/actions/clio-install
Run dotnet tool install clio --tool-path .\ClioTool
You can invoke the tool using the following command: clio
Tool 'clio' (version '6.0.1.3[2](https://github.com/unusen/BiogenesisBagoCreatio/actions/runs/5546096154/jobs/10125926515#step:4:2)') was successfully installed.
Run .\ClioTool\clio.exe install BiogenesisBago -u *** -l *** -p ***;
Uploading...
Uploaded
Backup process...
Backup completed
Install BiogenesisBago.gz ...
Installation log:
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request)
   at Creatio.Client.CreatioClient.PingApp(Int[32](https://github.com/unusen/BiogenesisBagoCreatio/actions/runs/5546096154/jobs/10125926515#step:4:35) pingTimeout)
   at Creatio.Client.CreatioClient.InitAuthCookie(Int32 requestTimeout)
   at Creatio.Client.CreatioClient.get_AuthCookie()
   at Creatio.Client.CreatioClient.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Common.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Package.BasePackageInstaller.InstallPackageOnServer(String fileName, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackageOnServerWithLogListener(String fileName, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackedPackage(String filePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackageFromFolder(String packageFolderPath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InstallPackage(String packagePackedFileOrFolderPath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions)
   at Clio.Package.BasePackageInstaller.InternalInstall(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
   at Clio.Package.PackageInstaller.Install(String packagePath, EnvironmentSettings environmentSettings, PackageInstallOptions packageInstallOptions, String reportPath)
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)
Error: Process completed with exit code 1.

We used this same action before and we received errors but the installation was completed succesfully.
Now same action raise error and the installation was not completed succesfully.
If we use Clio locally everything working as expected

Appreciate your help
Regards

**Comment by kirillkrylov** [comment]
@unusen
Please try new version 6.0.1.34
