### ISSUE TITLE
package size or image problems

### ISSUE THREAD

**Issue by igordyachkov** [Advance-Technologies-Foundation/clio#242]
Does the utility have limits on the size of packages that can be installed?
Or restrictions when adding images to a package?

Case:

1. Package size 17mb - installation passes
2. Pictures in base64 format are bound to the same packages as data. The size of the packages becomes 42 mb and the installation fails.

Error:

dotnet /opt/clio/clio.dll push-pkg /home/bcm_worker/workspace/b2ccrm/QA/qa/packages.zip -u http://*********:9003 -l ****** -p ****** -i true -r /home/bcm_worker/workspace/b2ccrm/QA/qa/logs/clio_PushPkg_1c27c7f44ea769fdb8c25aebb5341e25f6788fba.txt
Uploading...
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request)
   at Creatio.Client.CreatioClient.UploadFile(String url, String filePath)
   at Clio.Common.CreatioClientAdapter.UploadFile(String url, String filePath)
   at Clio.Package.PackageInstaller.UploadPackage(String filePath)
   at Clio.Package.PackageInstaller.InstallPackedPackage(String filePath)
   at Clio.Package.PackageInstaller.InstallPackage(String packagePackedFileOrFolderPath)
   at Clio.Package.PackageInstaller.Install(String packagePath, String reportPath)
   at Clio.Command.PushPackageCommand.Execute(PushPkgOptions options)

Translated with www.DeepL.com/Translator (free version)

**Comment by vladimir-nikonov** [comment]
Hi @igordyachkov Creatio and clio not contains limit for package size, but hosting system may have it. You can reade more information [this](https://www.inflectra.com/Support/KnowledgeBase/KB306.aspx)
