### ISSUE TITLE
Last version check leads to "rate limit exceeded" error

### ISSUE THREAD

**Issue by o-serhiichyk** [Advance-Technologies-Foundation/clio#291]
When clio is installed and used for some time with `"Autoupdate": true`, any command may result in the following error:

> Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Clio.Command.UpdateCliCommand.UpdateCliCommand.GetLatestVersion()
   at Clio.Command.UpdateCliCommand.UpdateCliCommand.CheckUpdate()
   at System.Threading.Thread.StartCallback()

This also leads to breaking clio-explorer extension.

**Comment by vladimir-nikonov** [comment]
The bug was fixed in 6.1.0.16+
