### ISSUE TITLE
clio apply-manifest error 

### ISSUE THREAD

**Issue by sergeytkachenko** [Advance-Technologies-Foundation/clio#292]
I have postgres studio application - 8.1.4 version.
When I try run command `apply-manifest /app/manifest.yaml -e app1` then I get an error:

**Runtime logs**:
```
Environment app1 was configured...
Uploading...
Uploaded
Backup process...
Backup completed
Install cliogate.gz ...
Installation log:
2024-05-13 18:01:43,079 Loading file: cliogate.gz 100%
2024-05-13 18:01:43,892 Configuration backup started.
2024-05-13 18:01:43,970 Loading packages from archive
2024-05-13 18:01:44,048 Package "cliogate" loaded
2024-05-13 18:01:44,064 Loading packages from database
2024-05-13 18:01:49,704 Loading packages from database
2024-05-13 18:01:56,251 Configuration backup successfully created.
2024-05-13 18:01:57,126 Preparing packages for installation
2024-05-13 18:01:57,142 Starting package installation
2024-05-13 18:01:57,157 Loading packages from archive
2024-05-13 18:01:57,220 Package "cliogate" loaded
2024-05-13 18:01:57,251 Loading packages from database
2024-05-13 18:02:02,798 Composing packages
2024-05-13 18:02:03,236 Package "cliogate" saved
2024-05-13 18:02:03,267 Modified - dependencies of package "cliogate"
2024-05-13 18:02:03,376 Modified - resources in package "cliogate"
2024-05-13 18:02:03,423 Modified - schema caption localizations in package "cliogate"
2024-05-13 18:02:03,580 Updating tables structure in database
2024-05-13 18:02:03,611 Updating modified schemas
2024-05-13 18:02:03,611 Updated modified schemas
2024-05-13 18:02:03,643 Installing data
2024-05-13 18:02:03,924 Configuration build started
2024-05-13 18:02:03,955 Current schemas info loaded
2024-05-13 18:02:04,111 New schemas info loaded
2024-05-13 18:02:04,127 Configuration state loaded
2024-05-13 18:02:04,142 Configuration server content generation started
2024-05-13 18:02:04,142 Configuration server content generated
2024-05-13 18:02:04,221 Meta info file updated
2024-05-13 18:02:04,236 File content generation started
2024-05-13 18:02:04,330 File content descriptors obtained
2024-05-13 18:02:04,392 File content descriptors generated
2024-05-13 18:02:04,408 File content bootstraps generated
2024-05-13 18:02:04,408 Configuration build finished
2024-05-13 18:02:04,517 Package installation finished
Done
Restart application...
[INF] - http://ts1-infr-web02:88/studioenu_6670986_0513
[ERR] - Object reference not set to an instance of an object.
```

### How to reproduce with `docker compose`:
1. Download docker-compose files - https://github.com/Advance-Technologies-Foundation/clio/files/15296534/install.zip
2. Unzip install.zip 
3. `cd install`
4. Change creatio url (entrypoint.sh & manifest.yaml) from `http://studio-postressql-app:5000` to `YOU_CREATIO_URL`
5. docker-compose run clio

### How to reproduce with `local clio`:
1. Download docker-compose files - https://github.com/Advance-Technologies-Foundation/clio/files/15296534/install.zip
2. Unzip install.zip 
3. `cd install`
4. Change creatio url (manifest.yaml) from `http://studio-postressql-app:5000` to `YOU_CREATIO_URL`
5. 
```
clio reg-web-app app1 --uri `YOU_CREATIO_URL` --Login Supervisor --Password Supervisor
clio install-gate -e app1
clio apply-manifest ./manifest.yaml -e app1
```

[install.zip](https://github.com/Advance-Technologies-Foundation/clio/files/15296534/install.zip)

**Comment by vladimir-nikonov** [comment]
@sergeytkachenko, try to remove the install gate command from your script. Apply manifest command don`t use clio API

**Comment by sergeytkachenko** [comment]
> @sergeytkachenko, try to remove the install gate command from your script. Apply manifest command don`t use clio API

I try execute only `dotnet /app/clio.dll apply-manifest /app/manifest.yaml` without other commands, but it didn't help. And when i build clio in local laptop (mac os), I have similar error - `Object reference not set to an instance of an object.`.

Then I added additional logs for [RemoteDataProvider](https://github.com/Advance-Technologies-Foundation/repository/blob/a3910c839014dea5ded6501a87bdb735d338fbb0/ATF.Repository/Providers/RemoteDataProvider.cs#L16):
<img width="834" alt="RemoteDataProvider" src="https://github.com/Advance-Technologies-Foundation/clio/assets/917149/d5e25691-8b5f-4c83-b232-fba746cac6da">

```
System.MissingMethodException: Method not found: 'System.String Creatio.Client.CreatioClient.ExecutePostRequest(System.String, System.String, Int32)'.
   at ATF.Repository.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at ATF.Repository.Providers.RemoteDataProvider.GetItems(ISelectQuery selectQuery) in /Users/mac/projects/repository/ATF.Repository/Providers/RemoteDataProvider.cs:line 123
```

Could it be because the projects that clio depends on, **have a different TargetFramework**?
