### ISSUE TITLE
Cannot execute clio get-pkg-list

### ISSUE THREAD

**Issue by swaggoo** [Advance-Technologies-Foundation/clio#310]
As far as I know, package version is optional. Please fix it

$ clio get-pkg-list         
System.Collections.Generic.KeyNotFoundException: The given key 'Version' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Clio.Package.ApplicationPackageListProvider.CreatePackageInfo(Dictionary`2 package)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Clio.Command.GetPkgListCommand.PrintPackageList(PkgListOptions options, IEnumerable`1 filteredPackages)
   at Clio.Command.GetPkgListCommand.Execute(PkgListOptions options)

**Comment by vladimir-nikonov** [comment]
fix in version 6.1.0.36
