### ISSUE TITLE
error while deploying using push-pkg

### ISSUE THREAD

**Issue by QualysoftCxmAT** [Advance-Technologies-Foundation/clio#316]
Hello,

we use clio intensively in our CI/CD pipelines, but we often encounter the following issue when using clio push-pkg:

`Uploading...
Uploaded
Backup process...
Backup completed
Install XYZ.gz ...
Installation log:
2024-09-16 16:22:35,728 Loading file: XYZ.gz 100%
2024-09-16 16:22:36,150 Configuration backup started.
2024-09-16 16:22:36,182 System.IO.DirectoryNotFoundException: Could not find a part of the path 'XYZ.gz'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Terrasoft.Core.ServiceModelContract.PackageInstaller.PackageInstallerServiceInternal.<>c__DisplayClass29_0.<CreateBackup>b__0()
   at Terrasoft.Core.ServiceModelContract.PackageInstaller.BaseInstallerServiceInternal.InvokeWithLogging(Action action)
2024-09-16 16:22:36,463 Preparing packages for installation
2024-09-16 16:22:36,478 Starting package installation
2024-09-16 16:22:36,510 Loading packages from archive
2024-09-16 16:22:39,041 System.IO.IOException: The directory is not empty.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Terrasoft.Common.IO.DirectoryWrapper.CreateOrReplaceDirectory(String path)
   at Terrasoft.Core.Packages.PackageZipFileStorage.CreateOrClearStorageDirectory()
   at Terrasoft.Core.Packages.PackageZipFileStorage.UnZipPackages()
   at Terrasoft.Core.Packages.PackageZipFileStorage.UnZipPackages(Boolean reuseUnzippedPackages)
   at Terrasoft.Core.Packages.PackageZipFileStorage.LoadInternal()
   at Terrasoft.Core.Packages.PackageStorage.Load()
   at Terrasoft.Core.Applications.Packages.Operations.PackageZipOperations.Load()
   at Terrasoft.Core.Applications.Installation.PackageZipInstaller.LoadPackages(String sourcePath, String destinationPath, Boolean excludeDeactivatedPackages)
   at Terrasoft.Core.Applications.Installation.PackageZipInstaller.Install(String sourcePath, String destinationPath, PackageInstallOptions installOptions)
   at Terrasoft.Core.ServiceModelContract.PackageInstaller.PackageInstallerServiceInternal.InstallFromUnzippedFiles(String sourcePath, String tempFilesPath, PackageInstallOptions packageInstallOptions)
   at Terrasoft.Core.ServiceModelContract.PackageInstaller.BaseInstallerServiceInternal.InvokeWithLogging[TResult](Func`1 action)
Error
##[error]PowerShell exited with code '1'.`

What path causes the problem, and how can we come by the issue?

Thanks,
Robert

**Comment by kirillkrylov** [comment]
@QualysoftCxmAT 

Hello Robert,

The issues seem to be on the Creatio side and not clio. The error message is from Creatio when it is trying to install the package. You should look into the logs of that instance. If you need help with this issue, please raise it with the Creatio support team.

I’m closing this issue as it is not related to clio.

Thanks.
