### ISSUE TITLE
Clio.Command.NewPkgCommand not found

### ISSUE THREAD

**Issue by kmwtw2024** [Advance-Technologies-Foundation/clio#334]
Hello,
I just installed clio and when I try to add package by clio command I am getting error below:
```
PS C:\CreatioDemo\Terrasoft.WebApp\Terrasoft.Configuration\Pkg> clio init AccelerateCustomProcess --debug
[ERR] - System.MissingMethodException: Constructor on type 'Clio.Command.NewPkgCommand' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Clio.Program.CreateCommand[TCommand](Object[] additionalConstructorArgs)
   at Clio.Program.<>c.<.cctor>b__94_0(Object instance)
   at Clio.Program.ExecuteCommands(String[] args)
   at Clio.Program.Main(String[] args)
```

**Comment by kirillkrylov** [comment]
Closed in version 8.0.1.5
